/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuthRoles {
  #[serde(rename = "roles")]
  roles: Option<Vec<::models::AuthRoleExtended>>
}

impl AuthRoles {
  pub fn new() -> AuthRoles {
    AuthRoles {
      roles: None
    }
  }

  pub fn set_roles(&mut self, roles: Vec<::models::AuthRoleExtended>) {
    self.roles = Some(roles);
  }

  pub fn with_roles(mut self, roles: Vec<::models::AuthRoleExtended>) -> AuthRoles {
    self.roles = Some(roles);
    self
  }

  pub fn roles(&self) -> Option<&Vec<::models::AuthRoleExtended>> {
    self.roles.as_ref()
  }

  pub fn reset_roles(&mut self) {
    self.roles = None;
  }

}



