/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuthNetgroups {
  #[serde(rename = "netgroups")]
  netgroups: Option<Vec<::models::AuthNetgroup>>
}

impl AuthNetgroups {
  pub fn new() -> AuthNetgroups {
    AuthNetgroups {
      netgroups: None
    }
  }

  pub fn set_netgroups(&mut self, netgroups: Vec<::models::AuthNetgroup>) {
    self.netgroups = Some(netgroups);
  }

  pub fn with_netgroups(mut self, netgroups: Vec<::models::AuthNetgroup>) -> AuthNetgroups {
    self.netgroups = Some(netgroups);
    self
  }

  pub fn netgroups(&self) -> Option<&Vec<::models::AuthNetgroup>> {
    self.netgroups.as_ref()
  }

  pub fn reset_netgroups(&mut self) {
    self.netgroups = None;
  }

}



