/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuthId {
  /// Specifies properties for a security token for the currently authenticated user.
  #[serde(rename = "ntoken")]
  ntoken: Option<::models::AuthIdNtoken>
}

impl AuthId {
  pub fn new() -> AuthId {
    AuthId {
      ntoken: None
    }
  }

  pub fn set_ntoken(&mut self, ntoken: ::models::AuthIdNtoken) {
    self.ntoken = Some(ntoken);
  }

  pub fn with_ntoken(mut self, ntoken: ::models::AuthIdNtoken) -> AuthId {
    self.ntoken = Some(ntoken);
    self
  }

  pub fn ntoken(&self) -> Option<&::models::AuthIdNtoken> {
    self.ntoken.as_ref()
  }

  pub fn reset_ntoken(&mut self) {
    self.ntoken = None;
  }

}



