/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuthLogLevel {
  /// 
  #[serde(rename = "level")]
  level: Option<::models::AuthLogLevelLevel>
}

impl AuthLogLevel {
  pub fn new() -> AuthLogLevel {
    AuthLogLevel {
      level: None
    }
  }

  pub fn set_level(&mut self, level: ::models::AuthLogLevelLevel) {
    self.level = Some(level);
  }

  pub fn with_level(mut self, level: ::models::AuthLogLevelLevel) -> AuthLogLevel {
    self.level = Some(level);
    self
  }

  pub fn level(&self) -> Option<&::models::AuthLogLevelLevel> {
    self.level.as_ref()
  }

  pub fn reset_level(&mut self) {
    self.level = None;
  }

}



