/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CertificateServerCertificateFingerprint {
  /// Fingerprint hash algorithm
  #[serde(rename = "type")]
  _type: Option<String>,
  /// Fingerprint value
  #[serde(rename = "value")]
  value: Option<String>
}

impl CertificateServerCertificateFingerprint {
  pub fn new() -> CertificateServerCertificateFingerprint {
    CertificateServerCertificateFingerprint {
      _type: None,
      value: None
    }
  }

  pub fn set_type(&mut self, _type: String) {
    self._type = Some(_type);
  }

  pub fn with_type(mut self, _type: String) -> CertificateServerCertificateFingerprint {
    self._type = Some(_type);
    self
  }

  pub fn _type(&self) -> Option<&String> {
    self._type.as_ref()
  }

  pub fn reset_type(&mut self) {
    self._type = None;
  }

  pub fn set_value(&mut self, value: String) {
    self.value = Some(value);
  }

  pub fn with_value(mut self, value: String) -> CertificateServerCertificateFingerprint {
    self.value = Some(value);
    self
  }

  pub fn value(&self) -> Option<&String> {
    self.value.as_ref()
  }

  pub fn reset_value(&mut self) {
    self.value = None;
  }

}



