/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CloudAccess {
  #[serde(rename = "clusters")]
  clusters: Option<Vec<::models::CloudAccessCluster>>,
  /// Continue returning results from previous call using this token (token should come from the previous call, resume cannot be used with other options).
  #[serde(rename = "resume")]
  resume: Option<String>
}

impl CloudAccess {
  pub fn new() -> CloudAccess {
    CloudAccess {
      clusters: None,
      resume: None
    }
  }

  pub fn set_clusters(&mut self, clusters: Vec<::models::CloudAccessCluster>) {
    self.clusters = Some(clusters);
  }

  pub fn with_clusters(mut self, clusters: Vec<::models::CloudAccessCluster>) -> CloudAccess {
    self.clusters = Some(clusters);
    self
  }

  pub fn clusters(&self) -> Option<&Vec<::models::CloudAccessCluster>> {
    self.clusters.as_ref()
  }

  pub fn reset_clusters(&mut self) {
    self.clusters = None;
  }

  pub fn set_resume(&mut self, resume: String) {
    self.resume = Some(resume);
  }

  pub fn with_resume(mut self, resume: String) -> CloudAccess {
    self.resume = Some(resume);
    self
  }

  pub fn resume(&self) -> Option<&String> {
    self.resume.as_ref()
  }

  pub fn reset_resume(&mut self) {
    self.resume = None;
  }

}



