/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ClusterTimeExtendedExtended {
  /// The current time on the cluster as a UNIX epoch (seconds since 1/1/1970), as reported by this node.
  #[serde(rename = "time")]
  time: Option<i32>
}

impl ClusterTimeExtendedExtended {
  pub fn new() -> ClusterTimeExtendedExtended {
    ClusterTimeExtendedExtended {
      time: None
    }
  }

  pub fn set_time(&mut self, time: i32) {
    self.time = Some(time);
  }

  pub fn with_time(mut self, time: i32) -> ClusterTimeExtendedExtended {
    self.time = Some(time);
    self
  }

  pub fn time(&self) -> Option<&i32> {
    self.time.as_ref()
  }

  pub fn reset_time(&mut self) {
    self.time = None;
  }

}



