/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ClusterFirmwareProgress : Cluster wide firmware upgrade progress info.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ClusterFirmwareProgress {
  /// The different states of a  firmware upgrade. One of the following values: 'committed', 'upgrading', 'error'
  #[serde(rename = "cluster_state")]
  cluster_state: Option<String>
}

impl ClusterFirmwareProgress {
  /// Cluster wide firmware upgrade progress info.
  pub fn new() -> ClusterFirmwareProgress {
    ClusterFirmwareProgress {
      cluster_state: None
    }
  }

  pub fn set_cluster_state(&mut self, cluster_state: String) {
    self.cluster_state = Some(cluster_state);
  }

  pub fn with_cluster_state(mut self, cluster_state: String) -> ClusterFirmwareProgress {
    self.cluster_state = Some(cluster_state);
    self
  }

  pub fn cluster_state(&self) -> Option<&String> {
    self.cluster_state.as_ref()
  }

  pub fn reset_cluster_state(&mut self) {
    self.cluster_state = None;
  }

}



