/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ClusterRetryLastActionItem : Retry the last upgrade action, in-case the previous attempt failed.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ClusterRetryLastActionItem {
  /// List of the nodes or \"all\" where the last upgrade action can be retried.
  #[serde(rename = "nodes")]
  nodes: Option<Vec<i32>>
}

impl ClusterRetryLastActionItem {
  /// Retry the last upgrade action, in-case the previous attempt failed.
  pub fn new() -> ClusterRetryLastActionItem {
    ClusterRetryLastActionItem {
      nodes: None
    }
  }

  pub fn set_nodes(&mut self, nodes: Vec<i32>) {
    self.nodes = Some(nodes);
  }

  pub fn with_nodes(mut self, nodes: Vec<i32>) -> ClusterRetryLastActionItem {
    self.nodes = Some(nodes);
    self
  }

  pub fn nodes(&self) -> Option<&Vec<i32>> {
    self.nodes.as_ref()
  }

  pub fn reset_nodes(&mut self) {
    self.nodes = None;
  }

}



