/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct EventEventgroupDefinitionsExtended {
  #[serde(rename = "eventgroup-definitions")]
  eventgroup_definitions: Option<Vec<::models::EventEventgroupDefinitionsEventgroupDefinition>>,
  /// Continue returning results from previous call using this token (token should come from the previous call, resume cannot be used with other options).
  #[serde(rename = "resume")]
  resume: Option<String>,
  /// Total number of items available.
  #[serde(rename = "total")]
  total: Option<i32>
}

impl EventEventgroupDefinitionsExtended {
  pub fn new() -> EventEventgroupDefinitionsExtended {
    EventEventgroupDefinitionsExtended {
      eventgroup_definitions: None,
      resume: None,
      total: None
    }
  }

  pub fn set_eventgroup_definitions(&mut self, eventgroup_definitions: Vec<::models::EventEventgroupDefinitionsEventgroupDefinition>) {
    self.eventgroup_definitions = Some(eventgroup_definitions);
  }

  pub fn with_eventgroup_definitions(mut self, eventgroup_definitions: Vec<::models::EventEventgroupDefinitionsEventgroupDefinition>) -> EventEventgroupDefinitionsExtended {
    self.eventgroup_definitions = Some(eventgroup_definitions);
    self
  }

  pub fn eventgroup_definitions(&self) -> Option<&Vec<::models::EventEventgroupDefinitionsEventgroupDefinition>> {
    self.eventgroup_definitions.as_ref()
  }

  pub fn reset_eventgroup_definitions(&mut self) {
    self.eventgroup_definitions = None;
  }

  pub fn set_resume(&mut self, resume: String) {
    self.resume = Some(resume);
  }

  pub fn with_resume(mut self, resume: String) -> EventEventgroupDefinitionsExtended {
    self.resume = Some(resume);
    self
  }

  pub fn resume(&self) -> Option<&String> {
    self.resume.as_ref()
  }

  pub fn reset_resume(&mut self) {
    self.resume = None;
  }

  pub fn set_total(&mut self, total: i32) {
    self.total = Some(total);
  }

  pub fn with_total(mut self, total: i32) -> EventEventgroupDefinitionsExtended {
    self.total = Some(total);
    self
  }

  pub fn total(&self) -> Option<&i32> {
    self.total.as_ref()
  }

  pub fn reset_total(&mut self) {
    self.total = None;
  }

}



