/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FilepoolPolicyFileMatchingPatternOrCriteriaItem {
  #[serde(rename = "and_criteria")]
  and_criteria: Vec<::models::FilepoolPolicyFileMatchingPatternOrCriteriaItemAndCriteriaItem>
}

impl FilepoolPolicyFileMatchingPatternOrCriteriaItem {
  pub fn new(and_criteria: Vec<::models::FilepoolPolicyFileMatchingPatternOrCriteriaItemAndCriteriaItem>) -> FilepoolPolicyFileMatchingPatternOrCriteriaItem {
    FilepoolPolicyFileMatchingPatternOrCriteriaItem {
      and_criteria: and_criteria
    }
  }

  pub fn set_and_criteria(&mut self, and_criteria: Vec<::models::FilepoolPolicyFileMatchingPatternOrCriteriaItemAndCriteriaItem>) {
    self.and_criteria = and_criteria;
  }

  pub fn with_and_criteria(mut self, and_criteria: Vec<::models::FilepoolPolicyFileMatchingPatternOrCriteriaItemAndCriteriaItem>) -> FilepoolPolicyFileMatchingPatternOrCriteriaItem {
    self.and_criteria = and_criteria;
    self
  }

  pub fn and_criteria(&self) -> &Vec<::models::FilepoolPolicyFileMatchingPatternOrCriteriaItemAndCriteriaItem> {
    &self.and_criteria
  }


}



