/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct HardeningStatus {
  /// Hardening Status of the cluster.
  #[serde(rename = "status")]
  status: Option<::models::HardeningStatusStatus>
}

impl HardeningStatus {
  pub fn new() -> HardeningStatus {
    HardeningStatus {
      status: None
    }
  }

  pub fn set_status(&mut self, status: ::models::HardeningStatusStatus) {
    self.status = Some(status);
  }

  pub fn with_status(mut self, status: ::models::HardeningStatusStatus) -> HardeningStatus {
    self.status = Some(status);
    self
  }

  pub fn status(&self) -> Option<&::models::HardeningStatusStatus> {
    self.status.as_ref()
  }

  pub fn reset_status(&mut self) {
    self.status = None;
  }

}



