/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct HardeningState {
  /// The state of hardening operation on the cluster.
  #[serde(rename = "state")]
  state: Option<::models::HardeningStateState>
}

impl HardeningState {
  pub fn new() -> HardeningState {
    HardeningState {
      state: None
    }
  }

  pub fn set_state(&mut self, state: ::models::HardeningStateState) {
    self.state = Some(state);
  }

  pub fn with_state(mut self, state: ::models::HardeningStateState) -> HardeningState {
    self.state = Some(state);
    self
  }

  pub fn state(&self) -> Option<&::models::HardeningStateState> {
    self.state.as_ref()
  }

  pub fn reset_state(&mut self) {
    self.state = None;
  }

}



