/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IdResolutionPathsExtended {
  #[serde(rename = "paths")]
  paths: Option<Vec<::models::IdResolutionPath>>,
  #[serde(rename = "errors")]
  errors: Option<Vec<::models::IdResolutionPathsError>>,
  /// Continue returning results from previous call using this token (token should come from the previous call, resume cannot be used with other options).
  #[serde(rename = "resume")]
  resume: Option<String>,
  /// Total number of items available.
  #[serde(rename = "total")]
  total: Option<i32>
}

impl IdResolutionPathsExtended {
  pub fn new() -> IdResolutionPathsExtended {
    IdResolutionPathsExtended {
      paths: None,
      errors: None,
      resume: None,
      total: None
    }
  }

  pub fn set_paths(&mut self, paths: Vec<::models::IdResolutionPath>) {
    self.paths = Some(paths);
  }

  pub fn with_paths(mut self, paths: Vec<::models::IdResolutionPath>) -> IdResolutionPathsExtended {
    self.paths = Some(paths);
    self
  }

  pub fn paths(&self) -> Option<&Vec<::models::IdResolutionPath>> {
    self.paths.as_ref()
  }

  pub fn reset_paths(&mut self) {
    self.paths = None;
  }

  pub fn set_errors(&mut self, errors: Vec<::models::IdResolutionPathsError>) {
    self.errors = Some(errors);
  }

  pub fn with_errors(mut self, errors: Vec<::models::IdResolutionPathsError>) -> IdResolutionPathsExtended {
    self.errors = Some(errors);
    self
  }

  pub fn errors(&self) -> Option<&Vec<::models::IdResolutionPathsError>> {
    self.errors.as_ref()
  }

  pub fn reset_errors(&mut self) {
    self.errors = None;
  }

  pub fn set_resume(&mut self, resume: String) {
    self.resume = Some(resume);
  }

  pub fn with_resume(mut self, resume: String) -> IdResolutionPathsExtended {
    self.resume = Some(resume);
    self
  }

  pub fn resume(&self) -> Option<&String> {
    self.resume.as_ref()
  }

  pub fn reset_resume(&mut self) {
    self.resume = None;
  }

  pub fn set_total(&mut self, total: i32) {
    self.total = Some(total);
  }

  pub fn with_total(mut self, total: i32) -> IdResolutionPathsExtended {
    self.total = Some(total);
    self
  }

  pub fn total(&self) -> Option<&i32> {
    self.total.as_ref()
  }

  pub fn reset_total(&mut self) {
    self.total = None;
  }

}



