/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct JobRecent {
  #[serde(rename = "recent_jobs")]
  recent_jobs: Option<Vec<::models::JobJobExtended>>,
  /// Total number of items available.
  #[serde(rename = "total")]
  total: Option<i32>
}

impl JobRecent {
  pub fn new() -> JobRecent {
    JobRecent {
      recent_jobs: None,
      total: None
    }
  }

  pub fn set_recent_jobs(&mut self, recent_jobs: Vec<::models::JobJobExtended>) {
    self.recent_jobs = Some(recent_jobs);
  }

  pub fn with_recent_jobs(mut self, recent_jobs: Vec<::models::JobJobExtended>) -> JobRecent {
    self.recent_jobs = Some(recent_jobs);
    self
  }

  pub fn recent_jobs(&self) -> Option<&Vec<::models::JobJobExtended>> {
    self.recent_jobs.as_ref()
  }

  pub fn reset_recent_jobs(&mut self) {
    self.recent_jobs = None;
  }

  pub fn set_total(&mut self, total: i32) {
    self.total = Some(total);
  }

  pub fn with_total(mut self, total: i32) -> JobRecent {
    self.total = Some(total);
    self
  }

  pub fn total(&self) -> Option<&i32> {
    self.total.as_ref()
  }

  pub fn reset_total(&mut self) {
    self.total = None;
  }

}



