/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// NdmpContextsBackupExtended : Get NDMP Context List

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NdmpContextsBackupExtended {
  #[serde(rename = "contexts")]
  contexts: Option<Vec<::models::NdmpContextsBackupContext>>,
  /// Resume string returned by previous query.
  #[serde(rename = "resume")]
  resume: Option<String>,
  /// The number of ndmp contexts.
  #[serde(rename = "total")]
  total: Option<i32>
}

impl NdmpContextsBackupExtended {
  /// Get NDMP Context List
  pub fn new() -> NdmpContextsBackupExtended {
    NdmpContextsBackupExtended {
      contexts: None,
      resume: None,
      total: None
    }
  }

  pub fn set_contexts(&mut self, contexts: Vec<::models::NdmpContextsBackupContext>) {
    self.contexts = Some(contexts);
  }

  pub fn with_contexts(mut self, contexts: Vec<::models::NdmpContextsBackupContext>) -> NdmpContextsBackupExtended {
    self.contexts = Some(contexts);
    self
  }

  pub fn contexts(&self) -> Option<&Vec<::models::NdmpContextsBackupContext>> {
    self.contexts.as_ref()
  }

  pub fn reset_contexts(&mut self) {
    self.contexts = None;
  }

  pub fn set_resume(&mut self, resume: String) {
    self.resume = Some(resume);
  }

  pub fn with_resume(mut self, resume: String) -> NdmpContextsBackupExtended {
    self.resume = Some(resume);
    self
  }

  pub fn resume(&self) -> Option<&String> {
    self.resume.as_ref()
  }

  pub fn reset_resume(&mut self) {
    self.resume = None;
  }

  pub fn set_total(&mut self, total: i32) {
    self.total = Some(total);
  }

  pub fn with_total(mut self, total: i32) -> NdmpContextsBackupExtended {
    self.total = Some(total);
    self
  }

  pub fn total(&self) -> Option<&i32> {
    self.total.as_ref()
  }

  pub fn reset_total(&mut self) {
    self.total = None;
  }

}



