/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// NdmpSettingsVariables : Get list of preferred environment variable.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NdmpSettingsVariables {
  /// Resume string returned by previous query.
  #[serde(rename = "resume")]
  resume: Option<String>,
  /// The number of backup paths.
  #[serde(rename = "total")]
  total: Option<i32>,
  #[serde(rename = "variables")]
  variables: Option<Vec<::models::NdmpSettingsVariablesVariable>>
}

impl NdmpSettingsVariables {
  /// Get list of preferred environment variable.
  pub fn new() -> NdmpSettingsVariables {
    NdmpSettingsVariables {
      resume: None,
      total: None,
      variables: None
    }
  }

  pub fn set_resume(&mut self, resume: String) {
    self.resume = Some(resume);
  }

  pub fn with_resume(mut self, resume: String) -> NdmpSettingsVariables {
    self.resume = Some(resume);
    self
  }

  pub fn resume(&self) -> Option<&String> {
    self.resume.as_ref()
  }

  pub fn reset_resume(&mut self) {
    self.resume = None;
  }

  pub fn set_total(&mut self, total: i32) {
    self.total = Some(total);
  }

  pub fn with_total(mut self, total: i32) -> NdmpSettingsVariables {
    self.total = Some(total);
    self
  }

  pub fn total(&self) -> Option<&i32> {
    self.total.as_ref()
  }

  pub fn reset_total(&mut self) {
    self.total = None;
  }

  pub fn set_variables(&mut self, variables: Vec<::models::NdmpSettingsVariablesVariable>) {
    self.variables = Some(variables);
  }

  pub fn with_variables(mut self, variables: Vec<::models::NdmpSettingsVariablesVariable>) -> NdmpSettingsVariables {
    self.variables = Some(variables);
    self
  }

  pub fn variables(&self) -> Option<&Vec<::models::NdmpSettingsVariablesVariable>> {
    self.variables.as_ref()
  }

  pub fn reset_variables(&mut self) {
    self.variables = None;
  }

}



