/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NetworkPool {
  /// Name of a valid access zone to map IP address pool to the zone.
  #[serde(rename = "access_zone")]
  access_zone: Option<String>,
  /// IP address format.
  #[serde(rename = "addr_family")]
  addr_family: Option<String>,
  /// OneFS supports the following NIC aggregation modes.
  #[serde(rename = "aggregation_mode")]
  aggregation_mode: Option<String>,
  /// Specifies how IP address allocation is done among pool members.
  #[serde(rename = "alloc_method")]
  alloc_method: Option<String>,
  /// A description of the pool.
  #[serde(rename = "description")]
  description: Option<String>,
  /// Name of the groupnet this pool belongs to.
  #[serde(rename = "groupnet")]
  groupnet: Option<String>,
  /// Unique Pool ID.
  #[serde(rename = "id")]
  id: Option<String>,
  /// List of interface members in this pool.
  #[serde(rename = "ifaces")]
  ifaces: Option<Vec<::models::SubnetsSubnetPoolIface>>,
  /// The name of the pool. It must be unique throughout the given subnet.It's a required field with POST method.
  #[serde(rename = "name")]
  name: Option<String>,
  /// List of IP address ranges in this pool.
  #[serde(rename = "ranges")]
  ranges: Option<Vec<::models::SubnetsSubnetPoolRange>>,
  /// Rebalance policy..
  #[serde(rename = "rebalance_policy")]
  rebalance_policy: Option<String>,
  /// Names of the rules in this pool.
  #[serde(rename = "rules")]
  rules: Option<Vec<String>>,
  /// Time delay in seconds before a node which has been                 automatically unsuspended becomes usable in SmartConnect                responses for pool zones.
  #[serde(rename = "sc_auto_unsuspend_delay")]
  sc_auto_unsuspend_delay: Option<i32>,
  /// SmartConnect client connection balancing policy.
  #[serde(rename = "sc_connect_policy")]
  sc_connect_policy: Option<String>,
  /// SmartConnect zone name for the pool.
  #[serde(rename = "sc_dns_zone")]
  sc_dns_zone: Option<String>,
  /// List of SmartConnect zone aliases (DNS names) to the pool.
  #[serde(rename = "sc_dns_zone_aliases")]
  sc_dns_zone_aliases: Option<Vec<String>>,
  /// SmartConnect IP failover policy.
  #[serde(rename = "sc_failover_policy")]
  sc_failover_policy: Option<String>,
  /// Name of SmartConnect service subnet for this pool.
  #[serde(rename = "sc_subnet")]
  sc_subnet: Option<String>,
  /// List of LNNs showing currently suspended nodes in SmartConnect.
  #[serde(rename = "sc_suspended_nodes")]
  sc_suspended_nodes: Option<Vec<i32>>,
  /// Time to live value for SmartConnect DNS query responses in seconds.
  #[serde(rename = "sc_ttl")]
  sc_ttl: Option<i32>,
  /// List of interface members in this pool.
  #[serde(rename = "static_routes")]
  static_routes: Option<Vec<::models::SubnetsSubnetPoolStaticRoute>>,
  /// The name of the subnet.
  #[serde(rename = "subnet")]
  subnet: Option<String>
}

impl NetworkPool {
  pub fn new() -> NetworkPool {
    NetworkPool {
      access_zone: None,
      addr_family: None,
      aggregation_mode: None,
      alloc_method: None,
      description: None,
      groupnet: None,
      id: None,
      ifaces: None,
      name: None,
      ranges: None,
      rebalance_policy: None,
      rules: None,
      sc_auto_unsuspend_delay: None,
      sc_connect_policy: None,
      sc_dns_zone: None,
      sc_dns_zone_aliases: None,
      sc_failover_policy: None,
      sc_subnet: None,
      sc_suspended_nodes: None,
      sc_ttl: None,
      static_routes: None,
      subnet: None
    }
  }

  pub fn set_access_zone(&mut self, access_zone: String) {
    self.access_zone = Some(access_zone);
  }

  pub fn with_access_zone(mut self, access_zone: String) -> NetworkPool {
    self.access_zone = Some(access_zone);
    self
  }

  pub fn access_zone(&self) -> Option<&String> {
    self.access_zone.as_ref()
  }

  pub fn reset_access_zone(&mut self) {
    self.access_zone = None;
  }

  pub fn set_addr_family(&mut self, addr_family: String) {
    self.addr_family = Some(addr_family);
  }

  pub fn with_addr_family(mut self, addr_family: String) -> NetworkPool {
    self.addr_family = Some(addr_family);
    self
  }

  pub fn addr_family(&self) -> Option<&String> {
    self.addr_family.as_ref()
  }

  pub fn reset_addr_family(&mut self) {
    self.addr_family = None;
  }

  pub fn set_aggregation_mode(&mut self, aggregation_mode: String) {
    self.aggregation_mode = Some(aggregation_mode);
  }

  pub fn with_aggregation_mode(mut self, aggregation_mode: String) -> NetworkPool {
    self.aggregation_mode = Some(aggregation_mode);
    self
  }

  pub fn aggregation_mode(&self) -> Option<&String> {
    self.aggregation_mode.as_ref()
  }

  pub fn reset_aggregation_mode(&mut self) {
    self.aggregation_mode = None;
  }

  pub fn set_alloc_method(&mut self, alloc_method: String) {
    self.alloc_method = Some(alloc_method);
  }

  pub fn with_alloc_method(mut self, alloc_method: String) -> NetworkPool {
    self.alloc_method = Some(alloc_method);
    self
  }

  pub fn alloc_method(&self) -> Option<&String> {
    self.alloc_method.as_ref()
  }

  pub fn reset_alloc_method(&mut self) {
    self.alloc_method = None;
  }

  pub fn set_description(&mut self, description: String) {
    self.description = Some(description);
  }

  pub fn with_description(mut self, description: String) -> NetworkPool {
    self.description = Some(description);
    self
  }

  pub fn description(&self) -> Option<&String> {
    self.description.as_ref()
  }

  pub fn reset_description(&mut self) {
    self.description = None;
  }

  pub fn set_groupnet(&mut self, groupnet: String) {
    self.groupnet = Some(groupnet);
  }

  pub fn with_groupnet(mut self, groupnet: String) -> NetworkPool {
    self.groupnet = Some(groupnet);
    self
  }

  pub fn groupnet(&self) -> Option<&String> {
    self.groupnet.as_ref()
  }

  pub fn reset_groupnet(&mut self) {
    self.groupnet = None;
  }

  pub fn set_id(&mut self, id: String) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: String) -> NetworkPool {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&String> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_ifaces(&mut self, ifaces: Vec<::models::SubnetsSubnetPoolIface>) {
    self.ifaces = Some(ifaces);
  }

  pub fn with_ifaces(mut self, ifaces: Vec<::models::SubnetsSubnetPoolIface>) -> NetworkPool {
    self.ifaces = Some(ifaces);
    self
  }

  pub fn ifaces(&self) -> Option<&Vec<::models::SubnetsSubnetPoolIface>> {
    self.ifaces.as_ref()
  }

  pub fn reset_ifaces(&mut self) {
    self.ifaces = None;
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> NetworkPool {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

  pub fn set_ranges(&mut self, ranges: Vec<::models::SubnetsSubnetPoolRange>) {
    self.ranges = Some(ranges);
  }

  pub fn with_ranges(mut self, ranges: Vec<::models::SubnetsSubnetPoolRange>) -> NetworkPool {
    self.ranges = Some(ranges);
    self
  }

  pub fn ranges(&self) -> Option<&Vec<::models::SubnetsSubnetPoolRange>> {
    self.ranges.as_ref()
  }

  pub fn reset_ranges(&mut self) {
    self.ranges = None;
  }

  pub fn set_rebalance_policy(&mut self, rebalance_policy: String) {
    self.rebalance_policy = Some(rebalance_policy);
  }

  pub fn with_rebalance_policy(mut self, rebalance_policy: String) -> NetworkPool {
    self.rebalance_policy = Some(rebalance_policy);
    self
  }

  pub fn rebalance_policy(&self) -> Option<&String> {
    self.rebalance_policy.as_ref()
  }

  pub fn reset_rebalance_policy(&mut self) {
    self.rebalance_policy = None;
  }

  pub fn set_rules(&mut self, rules: Vec<String>) {
    self.rules = Some(rules);
  }

  pub fn with_rules(mut self, rules: Vec<String>) -> NetworkPool {
    self.rules = Some(rules);
    self
  }

  pub fn rules(&self) -> Option<&Vec<String>> {
    self.rules.as_ref()
  }

  pub fn reset_rules(&mut self) {
    self.rules = None;
  }

  pub fn set_sc_auto_unsuspend_delay(&mut self, sc_auto_unsuspend_delay: i32) {
    self.sc_auto_unsuspend_delay = Some(sc_auto_unsuspend_delay);
  }

  pub fn with_sc_auto_unsuspend_delay(mut self, sc_auto_unsuspend_delay: i32) -> NetworkPool {
    self.sc_auto_unsuspend_delay = Some(sc_auto_unsuspend_delay);
    self
  }

  pub fn sc_auto_unsuspend_delay(&self) -> Option<&i32> {
    self.sc_auto_unsuspend_delay.as_ref()
  }

  pub fn reset_sc_auto_unsuspend_delay(&mut self) {
    self.sc_auto_unsuspend_delay = None;
  }

  pub fn set_sc_connect_policy(&mut self, sc_connect_policy: String) {
    self.sc_connect_policy = Some(sc_connect_policy);
  }

  pub fn with_sc_connect_policy(mut self, sc_connect_policy: String) -> NetworkPool {
    self.sc_connect_policy = Some(sc_connect_policy);
    self
  }

  pub fn sc_connect_policy(&self) -> Option<&String> {
    self.sc_connect_policy.as_ref()
  }

  pub fn reset_sc_connect_policy(&mut self) {
    self.sc_connect_policy = None;
  }

  pub fn set_sc_dns_zone(&mut self, sc_dns_zone: String) {
    self.sc_dns_zone = Some(sc_dns_zone);
  }

  pub fn with_sc_dns_zone(mut self, sc_dns_zone: String) -> NetworkPool {
    self.sc_dns_zone = Some(sc_dns_zone);
    self
  }

  pub fn sc_dns_zone(&self) -> Option<&String> {
    self.sc_dns_zone.as_ref()
  }

  pub fn reset_sc_dns_zone(&mut self) {
    self.sc_dns_zone = None;
  }

  pub fn set_sc_dns_zone_aliases(&mut self, sc_dns_zone_aliases: Vec<String>) {
    self.sc_dns_zone_aliases = Some(sc_dns_zone_aliases);
  }

  pub fn with_sc_dns_zone_aliases(mut self, sc_dns_zone_aliases: Vec<String>) -> NetworkPool {
    self.sc_dns_zone_aliases = Some(sc_dns_zone_aliases);
    self
  }

  pub fn sc_dns_zone_aliases(&self) -> Option<&Vec<String>> {
    self.sc_dns_zone_aliases.as_ref()
  }

  pub fn reset_sc_dns_zone_aliases(&mut self) {
    self.sc_dns_zone_aliases = None;
  }

  pub fn set_sc_failover_policy(&mut self, sc_failover_policy: String) {
    self.sc_failover_policy = Some(sc_failover_policy);
  }

  pub fn with_sc_failover_policy(mut self, sc_failover_policy: String) -> NetworkPool {
    self.sc_failover_policy = Some(sc_failover_policy);
    self
  }

  pub fn sc_failover_policy(&self) -> Option<&String> {
    self.sc_failover_policy.as_ref()
  }

  pub fn reset_sc_failover_policy(&mut self) {
    self.sc_failover_policy = None;
  }

  pub fn set_sc_subnet(&mut self, sc_subnet: String) {
    self.sc_subnet = Some(sc_subnet);
  }

  pub fn with_sc_subnet(mut self, sc_subnet: String) -> NetworkPool {
    self.sc_subnet = Some(sc_subnet);
    self
  }

  pub fn sc_subnet(&self) -> Option<&String> {
    self.sc_subnet.as_ref()
  }

  pub fn reset_sc_subnet(&mut self) {
    self.sc_subnet = None;
  }

  pub fn set_sc_suspended_nodes(&mut self, sc_suspended_nodes: Vec<i32>) {
    self.sc_suspended_nodes = Some(sc_suspended_nodes);
  }

  pub fn with_sc_suspended_nodes(mut self, sc_suspended_nodes: Vec<i32>) -> NetworkPool {
    self.sc_suspended_nodes = Some(sc_suspended_nodes);
    self
  }

  pub fn sc_suspended_nodes(&self) -> Option<&Vec<i32>> {
    self.sc_suspended_nodes.as_ref()
  }

  pub fn reset_sc_suspended_nodes(&mut self) {
    self.sc_suspended_nodes = None;
  }

  pub fn set_sc_ttl(&mut self, sc_ttl: i32) {
    self.sc_ttl = Some(sc_ttl);
  }

  pub fn with_sc_ttl(mut self, sc_ttl: i32) -> NetworkPool {
    self.sc_ttl = Some(sc_ttl);
    self
  }

  pub fn sc_ttl(&self) -> Option<&i32> {
    self.sc_ttl.as_ref()
  }

  pub fn reset_sc_ttl(&mut self) {
    self.sc_ttl = None;
  }

  pub fn set_static_routes(&mut self, static_routes: Vec<::models::SubnetsSubnetPoolStaticRoute>) {
    self.static_routes = Some(static_routes);
  }

  pub fn with_static_routes(mut self, static_routes: Vec<::models::SubnetsSubnetPoolStaticRoute>) -> NetworkPool {
    self.static_routes = Some(static_routes);
    self
  }

  pub fn static_routes(&self) -> Option<&Vec<::models::SubnetsSubnetPoolStaticRoute>> {
    self.static_routes.as_ref()
  }

  pub fn reset_static_routes(&mut self) {
    self.static_routes = None;
  }

  pub fn set_subnet(&mut self, subnet: String) {
    self.subnet = Some(subnet);
  }

  pub fn with_subnet(mut self, subnet: String) -> NetworkPool {
    self.subnet = Some(subnet);
    self
  }

  pub fn subnet(&self) -> Option<&String> {
    self.subnet.as_ref()
  }

  pub fn reset_subnet(&mut self) {
    self.subnet = None;
  }

}



