/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NfsLogLevel {
  /// Valid NFS logging levels
  #[serde(rename = "level")]
  level: Option<String>
}

impl NfsLogLevel {
  pub fn new() -> NfsLogLevel {
    NfsLogLevel {
      level: None
    }
  }

  pub fn set_level(&mut self, level: String) {
    self.level = Some(level);
  }

  pub fn with_level(mut self, level: String) -> NfsLogLevel {
    self.level = Some(level);
    self
  }

  pub fn level(&self) -> Option<&String> {
    self.level.as_ref()
  }

  pub fn reset_level(&mut self) {
    self.level = None;
  }

}



