/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NfsExports {
  #[serde(rename = "exports")]
  exports: Option<Vec<::models::NfsExportExtended>>
}

impl NfsExports {
  pub fn new() -> NfsExports {
    NfsExports {
      exports: None
    }
  }

  pub fn set_exports(&mut self, exports: Vec<::models::NfsExportExtended>) {
    self.exports = Some(exports);
  }

  pub fn with_exports(mut self, exports: Vec<::models::NfsExportExtended>) -> NfsExports {
    self.exports = Some(exports);
    self
  }

  pub fn exports(&self) -> Option<&Vec<::models::NfsExportExtended>> {
    self.exports.as_ref()
  }

  pub fn reset_exports(&mut self) {
    self.exports = None;
  }

}



