/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// NodeDriveconfigExtended : An object containing a node's drive subsystem XML configuration file.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NodeDriveconfigExtended {
  /// Configuration settings for automatic replacement recognition (ARR).
  #[serde(rename = "automatic_replacement_recognition")]
  automatic_replacement_recognition: Option<::models::NodeDriveconfigNodeAutomaticReplacementRecognition>
}

impl NodeDriveconfigExtended {
  /// An object containing a node's drive subsystem XML configuration file.
  pub fn new() -> NodeDriveconfigExtended {
    NodeDriveconfigExtended {
      automatic_replacement_recognition: None
    }
  }

  pub fn set_automatic_replacement_recognition(&mut self, automatic_replacement_recognition: ::models::NodeDriveconfigNodeAutomaticReplacementRecognition) {
    self.automatic_replacement_recognition = Some(automatic_replacement_recognition);
  }

  pub fn with_automatic_replacement_recognition(mut self, automatic_replacement_recognition: ::models::NodeDriveconfigNodeAutomaticReplacementRecognition) -> NodeDriveconfigExtended {
    self.automatic_replacement_recognition = Some(automatic_replacement_recognition);
    self
  }

  pub fn automatic_replacement_recognition(&self) -> Option<&::models::NodeDriveconfigNodeAutomaticReplacementRecognition> {
    self.automatic_replacement_recognition.as_ref()
  }

  pub fn reset_automatic_replacement_recognition(&mut self) {
    self.automatic_replacement_recognition = None;
  }

}



