/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NodeDrivesPurposelistNode {
  /// Error message, if the HTTP status returned from this node was not 200.
  #[serde(rename = "error")]
  error: Option<String>,
  /// Node ID of the node reporting this information.
  #[serde(rename = "id")]
  id: Option<i32>,
  /// Logical node number of the node reporting this information.
  #[serde(rename = "lnn")]
  lnn: Option<i32>,
  /// List of the drive purposes available on this node.
  #[serde(rename = "purposes")]
  purposes: Option<Vec<::models::NodeDrivesPurposelistNodePurpose>>,
  /// Status of the HTTP response from this node if not 200.  If 200, this field does not appear.
  #[serde(rename = "status")]
  status: Option<i32>
}

impl NodeDrivesPurposelistNode {
  pub fn new() -> NodeDrivesPurposelistNode {
    NodeDrivesPurposelistNode {
      error: None,
      id: None,
      lnn: None,
      purposes: None,
      status: None
    }
  }

  pub fn set_error(&mut self, error: String) {
    self.error = Some(error);
  }

  pub fn with_error(mut self, error: String) -> NodeDrivesPurposelistNode {
    self.error = Some(error);
    self
  }

  pub fn error(&self) -> Option<&String> {
    self.error.as_ref()
  }

  pub fn reset_error(&mut self) {
    self.error = None;
  }

  pub fn set_id(&mut self, id: i32) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: i32) -> NodeDrivesPurposelistNode {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&i32> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_lnn(&mut self, lnn: i32) {
    self.lnn = Some(lnn);
  }

  pub fn with_lnn(mut self, lnn: i32) -> NodeDrivesPurposelistNode {
    self.lnn = Some(lnn);
    self
  }

  pub fn lnn(&self) -> Option<&i32> {
    self.lnn.as_ref()
  }

  pub fn reset_lnn(&mut self) {
    self.lnn = None;
  }

  pub fn set_purposes(&mut self, purposes: Vec<::models::NodeDrivesPurposelistNodePurpose>) {
    self.purposes = Some(purposes);
  }

  pub fn with_purposes(mut self, purposes: Vec<::models::NodeDrivesPurposelistNodePurpose>) -> NodeDrivesPurposelistNode {
    self.purposes = Some(purposes);
    self
  }

  pub fn purposes(&self) -> Option<&Vec<::models::NodeDrivesPurposelistNodePurpose>> {
    self.purposes.as_ref()
  }

  pub fn reset_purposes(&mut self) {
    self.purposes = None;
  }

  pub fn set_status(&mut self, status: i32) {
    self.status = Some(status);
  }

  pub fn with_status(mut self, status: i32) -> NodeDrivesPurposelistNode {
    self.status = Some(status);
    self
  }

  pub fn status(&self) -> Option<&i32> {
    self.status.as_ref()
  }

  pub fn reset_status(&mut self) {
    self.status = None;
  }

}



