/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ProvidersLocal {
  #[serde(rename = "local")]
  local: Option<Vec<::models::ProvidersLocalLocalItem>>
}

impl ProvidersLocal {
  pub fn new() -> ProvidersLocal {
    ProvidersLocal {
      local: None
    }
  }

  pub fn set_local(&mut self, local: Vec<::models::ProvidersLocalLocalItem>) {
    self.local = Some(local);
  }

  pub fn with_local(mut self, local: Vec<::models::ProvidersLocalLocalItem>) -> ProvidersLocal {
    self.local = Some(local);
    self
  }

  pub fn local(&self) -> Option<&Vec<::models::ProvidersLocalLocalItem>> {
    self.local.as_ref()
  }

  pub fn reset_local(&mut self) {
    self.local = None;
  }

}



