/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ProvidersSummary {
  #[serde(rename = "provider_instances")]
  provider_instances: Option<Vec<::models::ProvidersSummaryProviderInstance>>
}

impl ProvidersSummary {
  pub fn new() -> ProvidersSummary {
    ProvidersSummary {
      provider_instances: None
    }
  }

  pub fn set_provider_instances(&mut self, provider_instances: Vec<::models::ProvidersSummaryProviderInstance>) {
    self.provider_instances = Some(provider_instances);
  }

  pub fn with_provider_instances(mut self, provider_instances: Vec<::models::ProvidersSummaryProviderInstance>) -> ProvidersSummary {
    self.provider_instances = Some(provider_instances);
    self
  }

  pub fn provider_instances(&self) -> Option<&Vec<::models::ProvidersSummaryProviderInstance>> {
    self.provider_instances.as_ref()
  }

  pub fn reset_provider_instances(&mut self) {
    self.provider_instances = None;
  }

}



