/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SettingsMappings {
  #[serde(rename = "mappings")]
  mappings: Option<Vec<::models::SettingsMappingExtendedExtended>>
}

impl SettingsMappings {
  pub fn new() -> SettingsMappings {
    SettingsMappings {
      mappings: None
    }
  }

  pub fn set_mappings(&mut self, mappings: Vec<::models::SettingsMappingExtendedExtended>) {
    self.mappings = Some(mappings);
  }

  pub fn with_mappings(mut self, mappings: Vec<::models::SettingsMappingExtendedExtended>) -> SettingsMappings {
    self.mappings = Some(mappings);
    self
  }

  pub fn mappings(&self) -> Option<&Vec<::models::SettingsMappingExtendedExtended>> {
    self.mappings.as_ref()
  }

  pub fn reset_mappings(&mut self) {
    self.mappings = None;
  }

}



