/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SnapshotLocksExtended {
  #[serde(rename = "locks")]
  locks: Option<Vec<::models::SnapshotLockExtended>>,
  /// Resume token value to use in subsequent calls for continuation.
  #[serde(rename = "resume")]
  resume: Option<String>,
  /// Total number of items available.
  #[serde(rename = "total")]
  total: Option<i32>
}

impl SnapshotLocksExtended {
  pub fn new() -> SnapshotLocksExtended {
    SnapshotLocksExtended {
      locks: None,
      resume: None,
      total: None
    }
  }

  pub fn set_locks(&mut self, locks: Vec<::models::SnapshotLockExtended>) {
    self.locks = Some(locks);
  }

  pub fn with_locks(mut self, locks: Vec<::models::SnapshotLockExtended>) -> SnapshotLocksExtended {
    self.locks = Some(locks);
    self
  }

  pub fn locks(&self) -> Option<&Vec<::models::SnapshotLockExtended>> {
    self.locks.as_ref()
  }

  pub fn reset_locks(&mut self) {
    self.locks = None;
  }

  pub fn set_resume(&mut self, resume: String) {
    self.resume = Some(resume);
  }

  pub fn with_resume(mut self, resume: String) -> SnapshotLocksExtended {
    self.resume = Some(resume);
    self
  }

  pub fn resume(&self) -> Option<&String> {
    self.resume.as_ref()
  }

  pub fn reset_resume(&mut self) {
    self.resume = None;
  }

  pub fn set_total(&mut self, total: i32) {
    self.total = Some(total);
  }

  pub fn with_total(mut self, total: i32) -> SnapshotLocksExtended {
    self.total = Some(total);
    self
  }

  pub fn total(&self) -> Option<&i32> {
    self.total.as_ref()
  }

  pub fn reset_total(&mut self) {
    self.total = None;
  }

}



