/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SnapshotSchedulesExtended {
  /// Resume token value to use in subsequent calls for continuation.
  #[serde(rename = "resume")]
  resume: Option<String>,
  #[serde(rename = "schedules")]
  schedules: Option<Vec<::models::SnapshotScheduleExtendedExtended>>,
  /// Total number of items available.
  #[serde(rename = "total")]
  total: Option<i32>
}

impl SnapshotSchedulesExtended {
  pub fn new() -> SnapshotSchedulesExtended {
    SnapshotSchedulesExtended {
      resume: None,
      schedules: None,
      total: None
    }
  }

  pub fn set_resume(&mut self, resume: String) {
    self.resume = Some(resume);
  }

  pub fn with_resume(mut self, resume: String) -> SnapshotSchedulesExtended {
    self.resume = Some(resume);
    self
  }

  pub fn resume(&self) -> Option<&String> {
    self.resume.as_ref()
  }

  pub fn reset_resume(&mut self) {
    self.resume = None;
  }

  pub fn set_schedules(&mut self, schedules: Vec<::models::SnapshotScheduleExtendedExtended>) {
    self.schedules = Some(schedules);
  }

  pub fn with_schedules(mut self, schedules: Vec<::models::SnapshotScheduleExtendedExtended>) -> SnapshotSchedulesExtended {
    self.schedules = Some(schedules);
    self
  }

  pub fn schedules(&self) -> Option<&Vec<::models::SnapshotScheduleExtendedExtended>> {
    self.schedules.as_ref()
  }

  pub fn reset_schedules(&mut self) {
    self.schedules = None;
  }

  pub fn set_total(&mut self, total: i32) {
    self.total = Some(total);
  }

  pub fn with_total(mut self, total: i32) -> SnapshotSchedulesExtended {
    self.total = Some(total);
    self
  }

  pub fn total(&self) -> Option<&i32> {
    self.total.as_ref()
  }

  pub fn reset_total(&mut self) {
    self.total = None;
  }

}



