/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct StatisticsHistoryStatValue {
  /// Unix Epoch time in seconds that statistic was collected.
  #[serde(rename = "time")]
  time: i32,
  /// Key dependent value.
  #[serde(rename = "value")]
  value: String
}

impl StatisticsHistoryStatValue {
  pub fn new(time: i32, value: String) -> StatisticsHistoryStatValue {
    StatisticsHistoryStatValue {
      time: time,
      value: value
    }
  }

  pub fn set_time(&mut self, time: i32) {
    self.time = time;
  }

  pub fn with_time(mut self, time: i32) -> StatisticsHistoryStatValue {
    self.time = time;
    self
  }

  pub fn time(&self) -> &i32 {
    &self.time
  }


  pub fn set_value(&mut self, value: String) {
    self.value = value;
  }

  pub fn with_value(mut self, value: String) -> StatisticsHistoryStatValue {
    self.value = value;
    self
  }

  pub fn value(&self) -> &String {
    &self.value
  }


}



