/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SummaryProtocolStatsProtocolStatsProtocolDataItem {
  /// The name of the protocol operation.
  #[serde(rename = "name")]
  name: String,
  /// Protocol specific operations per second. This is a variable number of output fields depending on the protocol being displayed.
  #[serde(rename = "value")]
  value: String
}

impl SummaryProtocolStatsProtocolStatsProtocolDataItem {
  pub fn new(name: String, value: String) -> SummaryProtocolStatsProtocolStatsProtocolDataItem {
    SummaryProtocolStatsProtocolStatsProtocolDataItem {
      name: name,
      value: value
    }
  }

  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> SummaryProtocolStatsProtocolStatsProtocolDataItem {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }


  pub fn set_value(&mut self, value: String) {
    self.value = value;
  }

  pub fn with_value(mut self, value: String) -> SummaryProtocolStatsProtocolStatsProtocolDataItem {
    self.value = value;
    self
  }

  pub fn value(&self) -> &String {
    &self.value
  }


}



