/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SummaryClient {
  #[serde(rename = "client")]
  client: Option<Vec<::models::SummaryClientClientItem>>
}

impl SummaryClient {
  pub fn new() -> SummaryClient {
    SummaryClient {
      client: None
    }
  }

  pub fn set_client(&mut self, client: Vec<::models::SummaryClientClientItem>) {
    self.client = Some(client);
  }

  pub fn with_client(mut self, client: Vec<::models::SummaryClientClientItem>) -> SummaryClient {
    self.client = Some(client);
    self
  }

  pub fn client(&self) -> Option<&Vec<::models::SummaryClientClientItem>> {
    self.client.as_ref()
  }

  pub fn reset_client(&mut self) {
    self.client = None;
  }

}



