/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct WormSettings {
  /// Specifies global SmartLock (WORM) settings.
  #[serde(rename = "settings")]
  settings: Option<::models::WormSettingsSettings>
}

impl WormSettings {
  pub fn new() -> WormSettings {
    WormSettings {
      settings: None
    }
  }

  pub fn set_settings(&mut self, settings: ::models::WormSettingsSettings) {
    self.settings = Some(settings);
  }

  pub fn with_settings(mut self, settings: ::models::WormSettingsSettings) -> WormSettings {
    self.settings = Some(settings);
    self
  }

  pub fn settings(&self) -> Option<&::models::WormSettingsSettings> {
    self.settings.as_ref()
  }

  pub fn reset_settings(&mut self) {
    self.settings = None;
  }

}



