/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ZonesExtended {
  #[serde(rename = "zones")]
  zones: Option<Vec<::models::ZoneExtendedExtended>>
}

impl ZonesExtended {
  pub fn new() -> ZonesExtended {
    ZonesExtended {
      zones: None
    }
  }

  pub fn set_zones(&mut self, zones: Vec<::models::ZoneExtendedExtended>) {
    self.zones = Some(zones);
  }

  pub fn with_zones(mut self, zones: Vec<::models::ZoneExtendedExtended>) -> ZonesExtended {
    self.zones = Some(zones);
    self
  }

  pub fn zones(&self) -> Option<&Vec<::models::ZoneExtendedExtended>> {
    self.zones.as_ref()
  }

  pub fn reset_zones(&mut self) {
    self.zones = None;
  }

}



