/* 
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ZonesSummaryExtended {
  /// The summary of a collection of objects.
  #[serde(rename = "summary")]
  summary: Option<::models::ZonesSummarySummaryExtended>
}

impl ZonesSummaryExtended {
  pub fn new() -> ZonesSummaryExtended {
    ZonesSummaryExtended {
      summary: None
    }
  }

  pub fn set_summary(&mut self, summary: ::models::ZonesSummarySummaryExtended) {
    self.summary = Some(summary);
  }

  pub fn with_summary(mut self, summary: ::models::ZonesSummarySummaryExtended) -> ZonesSummaryExtended {
    self.summary = Some(summary);
    self
  }

  pub fn summary(&self) -> Option<&::models::ZonesSummarySummaryExtended> {
    self.summary.as_ref()
  }

  pub fn reset_summary(&mut self) {
    self.summary = None;
  }

}



